# WirePlumber Bluetooth tuning for this laptop.
monitor.bluez.properties = {
  bluez5.enable-sbc-xq = true
  bluez5.enable-msbc = true
  bluez5.roles = [ a2dp_sink a2dp_source hfp_hf hfp_ag ]
}

wireplumber.components.rules = [
  {
    matches = [
      {
        provides = "hardware.bluetooth"
      }
    ]
    actions = {
      override = {
        wants = [ monitor.bluez ]
      }
    }
  }
  {
    matches = [
      {
        name = "monitors/bluez-midi.lua"
      }
    ]
    actions = {
      override = {
        enable = false
      }
    }
  }
]
