# TMUX - GRUVBOX DARK HARD
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:Tc,xterm-256color:Tc"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -sg escape-time 0
set -g focus-events on
set -g detach-on-destroy off
set -g display-time 1800
set -g display-panes-time 1200
set -g set-clipboard on
set -g allow-passthrough on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind x kill-pane
bind X kill-window
bind r source-file ~/.config/tmux/tmux.conf \; display-message "TMUX CONFIG RELOADED"
bind a last-window
bind Space next-layout
bind f display-popup -E -w 90% -h 85% -b rounded -T " FILE MANAGER " "yazi"
bind g display-popup -E -w 90% -h 85% -b rounded -T " LAZYGIT " "lazygit"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5
bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2

setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind -T copy-mode-vi Escape send -X cancel

set -g pane-border-lines heavy
set -g popup-border-lines rounded

set -g status on
set -g status-position bottom
set -g status-interval 5
set -g status-bg "#1d2021"
set -g status-fg "#ebdbb2"
set -g status-left-length 40
set -g status-right-length 80
set -g status-left "#[bg=#fabd2f,fg=#1d2021,bold] #S #[bg=#1d2021,fg=#fabd2f] "
set -g status-right "#[fg=#8ec07c,bold] #h #[fg=#504945]│#[fg=#83a598,bold] %A %d/%m/%Y #[fg=#504945]│#[fg=#fabd2f,bold] %H:%M:%S "
setw -g window-status-separator ""
setw -g window-status-format "#[fg=#a89984] #I #[fg=#504945]│#[fg=#a89984] #W "
setw -g window-status-current-format "#[bg=#3c3836,fg=#fabd2f,bold] #I #[fg=#fbf1c7,bold] #W "
set -g pane-border-style "fg=#3c3836"
set -g pane-active-border-style "fg=#fbf1c7"
set -g message-style "bg=#282828,fg=#ebdbb2"
set -g mode-style "bg=#fabd2f,fg=#1d2021,bold"
set -g display-panes-active-colour "#fabd2f"
set -g display-panes-colour "#504945"
set -g clock-mode-colour "#fabd2f"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'

if-shell '[ -d ~/.tmux/plugins/tpm ]' 'run ~/.tmux/plugins/tpm/tpm'
