# Rifle associations for ranger
ext x?html?, has firefox, X, flag f = firefox -- "$@"
ext pdf, has zathura, X, flag f = zathura -- "$@"
ext pdf, has firefox, X, flag f = firefox -- "$@"
mime ^image, has feh, X, flag f = feh -- "$@"
mime ^video, has vlc, X, flag f = vlc -- "$@"
mime ^audio, has vlc, X, flag f = vlc -- "$@"
ext zip|rar|7z|tar|gz|bz2|xz, has file-roller, X, flag f = file-roller -- "$@"
label editor = "$EDITOR" -- "$@"
label pager = "$PAGER" -- "$@"
else = xdg-open "$1"
