return {
  {
    "ellisonleao/gruvbox.nvim",
    priority = 1000,
    opts = {
      terminal_colors = true,
      undercurl = true,
      underline = true,
      bold = true,
      italic = {
        strings = false,
        emphasis = true,
        comments = true,
        operators = false,
        folds = true,
      },
      strikethrough = true,
      invert_selection = false,
      invert_signs = false,
      invert_tabline = false,
      invert_intend_guides = false,
      inverse = true,
      contrast = "hard",
      palette_overrides = {
        dark0_hard = "#1d2021",
        dark0 = "#282828",
        dark1 = "#32302f",
        light0 = "#fbf1c7",
      },
      overrides = {
        Normal = { bg = "#1d2021", fg = "#fbf1c7" },
        NormalNC = { bg = "#1d2021", fg = "#d5c4a1" },
        NormalFloat = { bg = "#282828", fg = "#fbf1c7" },
        FloatBorder = { fg = "#ebdbb2", bg = "#282828" },
        CursorLine = { bg = "#282828" },
        LineNr = { fg = "#7c6f64" },
        CursorLineNr = { fg = "#fabd2f", bold = true },
        SignColumn = { bg = "#1d2021" },
        VertSplit = { fg = "#504945" },
        WinSeparator = { fg = "#504945" },
        Pmenu = { bg = "#282828", fg = "#ebdbb2" },
        PmenuSel = { bg = "#504945", fg = "#fbf1c7", bold = true },
        Search = { bg = "#d79921", fg = "#1d2021" },
        IncSearch = { bg = "#fabd2f", fg = "#1d2021" },
        Visual = { bg = "#504945" },
        DiagnosticError = { fg = "#fb4934" },
        DiagnosticWarn = { fg = "#fabd2f" },
        DiagnosticInfo = { fg = "#83a598" },
        DiagnosticHint = { fg = "#8ec07c" },
      },
      dim_inactive = false,
      transparent_mode = false,
    },
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "gruvbox",
    },
  },
}
