return {
  {
    "mason-org/mason.nvim",
    opts = function(_, opts)
      opts.ensure_installed = vim.list_extend(opts.ensure_installed or {}, {
        "lua-language-server",
        "stylua",
        "typescript-language-server",
        "eslint_d",
        "eslint-lsp",
        "prettier",
        "tailwindcss-language-server",
        "angular-language-server",
        "html-lsp",
        "css-lsp",
        "json-lsp",
        "yaml-language-server",
        "taplo",
        "dockerfile-language-server",
        "docker-compose-language-service",
        "terraform-ls",
        "hadolint",
        "marksman",
        "markdownlint",
        "pyright",
        "ruff",
        "debugpy",
        "rust-analyzer",
        "gopls",
        "goimports",
        "gofumpt",
        "delve",
        "clangd",
        "clang-format",
        "jdtls",
        "java-debug-adapter",
        "java-test",
        "omnisharp",
        "csharpier",
        "netcoredbg",
        "bash-language-server",
        "shellcheck",
        "shfmt",
        "sqlfluff",
      })

      opts.ensure_installed = vim.tbl_filter(function(tool)
        return tool ~= "codelldb" and tool ~= "cmake-language-server"
      end, opts.ensure_installed)
    end,
  },
  {
    "neovim/nvim-lspconfig",
    opts = {
      servers = {
        angularls = {},
        bashls = {},
        clangd = {},
        docker_compose_language_service = {},
        dockerls = {},
        cssls = {},
        gopls = {},
        html = {},
        jsonls = {},
        lua_ls = {},
        marksman = {},
        omnisharp = {
          enable_roslyn_analyzers = true,
          organize_imports_on_format = true,
        },
        pyright = {},
        ruff = {},
        rust_analyzer = {},
        sqlls = {},
        tailwindcss = {},
        taplo = {},
        terraformls = {},
        ts_ls = {},
        yamlls = {},
      },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = function(_, opts)
      opts.ensure_installed = vim.list_extend(opts.ensure_installed or {}, {
        "angular",
        "bash",
        "c",
        "c_sharp",
        "cmake",
        "cpp",
        "css",
        "dockerfile",
        "go",
        "gomod",
        "gosum",
        "html",
        "java",
        "javascript",
        "json",
        "jsonc",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "regex",
        "rust",
        "sql",
        "terraform",
        "hcl",
        "tsx",
        "typescript",
        "vim",
        "vimdoc",
        "yaml",
      })
    end,
  },
  {
    "stevearc/conform.nvim",
    opts = {
      formatters_by_ft = {
        javascript = { "prettier" },
        javascriptreact = { "prettier" },
        typescript = { "prettier" },
        typescriptreact = { "prettier" },
        angular = { "prettier" },
        css = { "prettier" },
        html = { "prettier" },
        json = { "prettier" },
        jsonc = { "prettier" },
        yaml = { "prettier" },
        markdown = { "prettier" },
        lua = { "stylua" },
        python = { "ruff_format" },
        rust = { "rustfmt" },
        go = { "goimports", "gofumpt" },
        c = { "clang_format" },
        cpp = { "clang_format" },
        cs = { "csharpier" },
        sh = { "shfmt" },
        sql = { "sqlfluff" },
        terraform = { "terraform_fmt" },
        hcl = { "terraform_fmt" },
      },
    },
  },
  {
    "mfussenegger/nvim-lint",
    opts = {
      linters_by_ft = {
        javascript = { "eslint_d" },
        javascriptreact = { "eslint_d" },
        typescript = { "eslint_d" },
        typescriptreact = { "eslint_d" },
        python = { "ruff" },
        markdown = { "markdownlint" },
        sh = { "shellcheck" },
        sql = { "sqlfluff" },
        dockerfile = { "hadolint" },
      },
    },
  },
}
